# https://www.zaproxy.org/docs/docker/baseline-scan/
# https://www.zaproxy.org/blog/2020-04-09-automate-security-testing-with-zap-and-github-actions/
name: Action Baseline Scan by OWASP ZAP

on:
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  zap_baseline_scan:
    runs-on: ubuntu-latest
    name: Zap Baseline Scan
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: ${{ secrets.TARGET_URL }}
          # rules_file_name: '.zap/rules.tsv'
          cmd_options: >
            -a
            -j
            -z "
            -config alert.maxInstances=0
            -config view.locale=ja_JP
            "
